\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=2.54cm]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Assignment 8: Time Series Analysis},
            pdfauthor={Felipe Raby Amadori},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Assignment 8: Time Series Analysis}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Felipe Raby Amadori}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
    \date{}
    \predate{}\postdate{}
  

\begin{document}
\maketitle

\subsection{OVERVIEW}\label{overview}

This exercise accompanies the lessons in Environmental Data Analytics
(ENV872L) on time series analysis.

\subsection{Directions}\label{directions}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Change ``Student Name'' on line 3 (above) with your name.
\item
  Use the lesson as a guide. It contains code that can be modified to
  complete the assignment.
\item
  Work through the steps, \textbf{creating code and output} that fulfill
  each instruction.
\item
  Be sure to \textbf{answer the questions} in this assignment document.
  Space for your answers is provided in this document and is indicated
  by the ``\textgreater{}'' character. If you need a second paragraph be
  sure to start the first line with ``\textgreater{}''. You should
  notice that the answer is highlighted in green by RStudio.
\item
  When you have completed the assignment, \textbf{Knit} the text and
  code into a single PDF file. You will need to have the correct
  software installed to do this (see Software Installation Guide) Press
  the \texttt{Knit} button in the RStudio scripting panel. This will
  save the PDF output in your Assignments folder.
\item
  After Knitting, please submit the completed exercise (PDF file) to the
  dropbox in Sakai. Please add your last name into the file name (e.g.,
  ``Salk\_A08\_TimeSeries.pdf'') prior to submission.
\end{enumerate}

The completed exercise is due on Tuesday, 19 March, 2019 before class
begins.

\subsection{Brainstorm a project
topic}\label{brainstorm-a-project-topic}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Spend 15 minutes brainstorming ideas for a project topic, and look for
  a dataset if you are choosing your own rather than using a class
  dataset. Remember your topic choices are due by the end of March, and
  you should post your choice ASAP to the forum on Sakai.
\end{enumerate}

Question: Did you do this?

\begin{quote}
ANSWER: Yes
\end{quote}

\subsection{Set up your session}\label{set-up-your-session}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Set up your session. Upload the EPA air quality raw dataset for PM2.5
  in 2018, and the processed NTL-LTER dataset for nutrients in Peter and
  Paul lakes. Build a ggplot theme and set it as your default theme.
  Make sure date variables are set to a date format.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\OperatorTok{::}\NormalTok{opts_chunk}\OperatorTok{$}\KeywordTok{set}\NormalTok{(}\DataTypeTok{echo =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{message =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{warning =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{eval=}\OtherTok{TRUE}\NormalTok{)}
\KeywordTok{getwd}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "C:/Users/Felipe/OneDrive - Duke University/1. DUKE/1. Ramos 2 Semestre/EOS-872 Env. Data Analytics/Environmental_Data_Analytics"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(FSA)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## ## FSA v0.8.22. See citation('FSA') if used in publication.
## ## Run fishR() for related website and fishR('IFAR') for related book.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching packages ----------------------------------------- tidyverse 1.2.1 --
\end{verbatim}

\begin{verbatim}
## v ggplot2 3.0.0     v purrr   0.2.5
## v tibble  1.4.2     v dplyr   0.7.6
## v tidyr   0.8.1     v stringr 1.3.1
## v readr   1.1.1     v forcats 0.3.0
\end{verbatim}

\begin{verbatim}
## -- Conflicts -------------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(RColorBrewer)}
\KeywordTok{library}\NormalTok{(ggpubr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: magrittr
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'magrittr'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:purrr':
## 
##     set_names
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:tidyr':
## 
##     extract
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(viridis)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: viridisLite
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(colormap)}
\KeywordTok{library}\NormalTok{(lubridate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'lubridate'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:base':
## 
##     date
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(nlme)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'nlme'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:dplyr':
## 
##     collapse
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(lsmeans)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: emmeans
\end{verbatim}

\begin{verbatim}
## The 'lsmeans' package is now basically a front end for 'emmeans'.
## Users are encouraged to switch the rest of the way.
## See help('transition') for more information, including how to
## convert old 'lsmeans' objects and scripts to work with 'emmeans'.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(multcompView)}
\KeywordTok{library}\NormalTok{(trend)}

\NormalTok{felipe_theme <-}\StringTok{ }\KeywordTok{theme_light}\NormalTok{(}\DataTypeTok{base_size =} \DecValTok{12}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{color =} \StringTok{"grey8"}\NormalTok{), }
        \DataTypeTok{legend.position =} \StringTok{"right"}\NormalTok{, }\DataTypeTok{plot.title =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }
\KeywordTok{theme_set}\NormalTok{(felipe_theme)}

\NormalTok{EPA_raw_AQ_PM25_}\DecValTok{2018}\NormalTok{ <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./Data/Raw/EPAair_PM25_NC2018_raw.csv"}\NormalTok{)}
\NormalTok{NTL_TER_raw_ChemistryNutr_PeterPaul <-}\StringTok{ }
\StringTok{  }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./Data/Processed/NTL-LTER_Lake_Chemistry_Nutrients_PeterPaul_Processed.csv"}\NormalTok{)}

\KeywordTok{class}\NormalTok{(EPA_raw_AQ_PM25_}\DecValTok{2018}\OperatorTok{$}\NormalTok{Date)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "factor"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{class}\NormalTok{(NTL_TER_raw_ChemistryNutr_PeterPaul}\OperatorTok{$}\NormalTok{sampledate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "factor"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{EPA_raw_AQ_PM25_}\DecValTok{2018}\OperatorTok{$}\NormalTok{Date <-}\StringTok{ }\KeywordTok{as.Date}\NormalTok{(EPA_raw_AQ_PM25_}\DecValTok{2018}\OperatorTok{$}\NormalTok{Date, }\DataTypeTok{format =} \StringTok{"%m/%d/%y"}\NormalTok{)}
\NormalTok{NTL_TER_raw_ChemistryNutr_PeterPaul}\OperatorTok{$}\NormalTok{sampledate <-}\StringTok{ }
\StringTok{  }\KeywordTok{as.Date}\NormalTok{(NTL_TER_raw_ChemistryNutr_PeterPaul}\OperatorTok{$}\NormalTok{sampledate, }\DataTypeTok{format =} \StringTok{"%Y-%m-%d"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Run a hierarchical (mixed-effects)
model}\label{run-a-hierarchical-mixed-effects-model}

Research question: Do PM2.5 concentrations have a significant trend in
2018?

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Run a repeated measures ANOVA, with PM2.5 concentrations as the
  response, Date as a fixed effect, and Site.Name as a random effect.
  This will allow us to extrapolate PM2.5 concentrations across North
  Carolina.
\end{enumerate}

3a. Illustrate PM2.5 concentrations by date. Do not split aesthetics by
site.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#3a.}

\KeywordTok{ggplot}\NormalTok{(EPA_raw_AQ_PM25_}\DecValTok{2018}\NormalTok{, }
       \KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Date, }\DataTypeTok{y =}\NormalTok{ Daily.Mean.PM2.}\FloatTok{5.}\NormalTok{Concentration, }\DataTypeTok{color =}\NormalTok{ Daily.Mean.PM2.}\FloatTok{5.}\NormalTok{Concentration)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{45}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_color_distiller}\NormalTok{(}\DataTypeTok{palette =} \StringTok{"Set1"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\KeywordTok{expression}\NormalTok{(}\StringTok{"Date"}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\KeywordTok{expression}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{"PM 2.5 Concentration (\textbackslash{}U003BCg/lt LC)"}\NormalTok{))) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position =} \StringTok{"none"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"2018 Daily PM2.5 concentration"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A08_TimeSeries_files/figure-latex/unnamed-chunk-2-1.pdf}

3b. Insert the following line of code into your R chunk. This will
eliminate duplicate measurements on single dates for each site. PM2.5 =
PM2.5{[}order(PM2.5{[},`Date'{]},-PM2.5{[},`Site.ID'{]}),{]} PM2.5 =
PM2.5{[}!duplicated(PM2.5\$Date),{]}

3c. Determine the temporal autocorrelation in your model.

3d. Run a mixed effects model.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#3b.}
\NormalTok{PM2.}\DecValTok{5}\NormalTok{ =}\StringTok{ }\NormalTok{EPA_raw_AQ_PM25_}\DecValTok{2018}\NormalTok{[}\KeywordTok{order}\NormalTok{(EPA_raw_AQ_PM25_}\DecValTok{2018}\NormalTok{[,}\StringTok{'Date'}\NormalTok{],}\OperatorTok{-}\NormalTok{EPA_raw_AQ_PM25_}\DecValTok{2018}\NormalTok{[,}\StringTok{'Site.ID'}\NormalTok{]),]}
\NormalTok{PM2.}\DecValTok{5}\NormalTok{ =}\StringTok{ }\NormalTok{PM2.}\DecValTok{5}\NormalTok{[}\OperatorTok{!}\KeywordTok{duplicated}\NormalTok{(PM2.}\DecValTok{5}\OperatorTok{$}\NormalTok{Date),]}

\CommentTok{#3c.}
\NormalTok{PM252018.auto <-}\StringTok{ }\KeywordTok{lme}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ EPA_raw_AQ_PM25_}\DecValTok{2018}\NormalTok{, Daily.Mean.PM2.}\FloatTok{5.}\NormalTok{Concentration }\OperatorTok{~}\StringTok{ }\NormalTok{Date, }
                     \DataTypeTok{random =} \OperatorTok{~}\DecValTok{1}\OperatorTok{|}\NormalTok{Site.Name)}
\NormalTok{PM252018.auto}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Linear mixed-effects model fit by REML
##   Data: EPA_raw_AQ_PM25_2018 
##   Log-restricted-likelihood: -20297.38
##   Fixed: Daily.Mean.PM2.5.Concentration ~ Date 
## (Intercept)        Date 
## 20.14183588 -0.00074241 
## 
## Random effects:
##  Formula: ~1 | Site.Name
##         (Intercept) Residual
## StdDev:    1.841425 3.457061
## 
## Number of Observations: 7611
## Number of Groups: 24
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ACF}\NormalTok{(PM252018.auto)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    lag          ACF
## 1    0  1.000000000
## 2    1  0.473017989
## 3    2  0.143093030
## 4    3  0.060500838
## 5    4  0.061574447
## 6    5  0.087756109
## 7    6  0.061116723
## 8    7  0.007595491
## 9    8  0.025491472
## 10   9  0.057872193
## 11  10  0.095911195
## 12  11  0.086519308
## 13  12  0.041507759
## 14  13  0.041091743
## 15  14  0.008663124
## 16  15 -0.012810524
## 17  16 -0.016388970
## 18  17 -0.023436707
## 19  18  0.020967717
## 20  19  0.032373855
## 21  20 -0.046770645
## 22  21 -0.086974675
## 23  22 -0.045009633
## 24  23  0.014507171
## 25  24  0.046279402
## 26  25  0.021031653
## 27  26 -0.017185250
## 28  27  0.008158717
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#3d.}
\NormalTok{PM252018.mixed <-}\StringTok{ }\KeywordTok{lme}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ PM2.}\DecValTok{5}\NormalTok{, Daily.Mean.PM2.}\FloatTok{5.}\NormalTok{Concentration }\OperatorTok{~}\StringTok{ }\NormalTok{Date, }
                     \DataTypeTok{random =} \OperatorTok{~}\DecValTok{1}\OperatorTok{|}\NormalTok{Site.Name,}
                     \DataTypeTok{correlation =} \KeywordTok{corAR1}\NormalTok{(}\DataTypeTok{form =} \OperatorTok{~}\StringTok{ }\NormalTok{Date}\OperatorTok{|}\NormalTok{Site.Name, }\DataTypeTok{value =} \FloatTok{0.473017989}\NormalTok{),}
                     \DataTypeTok{method =} \StringTok{"REML"}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(PM252018.mixed)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Linear mixed-effects model fit by REML
##  Data: PM2.5 
##        AIC      BIC   logLik
##   1756.622 1775.781 -873.311
## 
## Random effects:
##  Formula: ~1 | Site.Name
##          (Intercept) Residual
## StdDev: 0.0007705506 3.597269
## 
## Correlation Structure: ARMA(1,0)
##  Formula: ~Date | Site.Name 
##  Parameter estimate(s):
##      Phi1 
## 0.5384349 
## Fixed effects: Daily.Mean.PM2.5.Concentration ~ Date 
##                Value Std.Error  DF   t-value p-value
## (Intercept) 83.14801  60.63584 339  1.371268  0.1712
## Date        -0.00426   0.00342 339 -1.244145  0.2143
##  Correlation: 
##      (Intr)
## Date -1    
## 
## Standardized Within-Group Residuals:
##        Min         Q1        Med         Q3        Max 
## -2.3220745 -0.6187194 -0.1116751  0.6164257  3.4192603 
## 
## Number of Observations: 343
## Number of Groups: 3
\end{verbatim}

Is there a significant increasing or decreasing trend in PM2.5
concentrations in 2018?

\begin{quote}
ANSWER: There is not a significant decrease trend in PM2.5
concentrations in 2018 (Linear mixed-effects model, p-value = 0.2143
\textgreater{} 0.05).
\end{quote}

3e. Run a fixed effects model with Date as the only explanatory
variable. Then test whether the mixed effects model is a better fit than
the fixed effect model.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PM252018.fixed <-}\StringTok{ }\KeywordTok{gls}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ PM2.}\DecValTok{5}\NormalTok{, Daily.Mean.PM2.}\FloatTok{5.}\NormalTok{Concentration }\OperatorTok{~}\StringTok{ }\NormalTok{Date, }\DataTypeTok{method =} \StringTok{"REML"}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(PM252018.fixed)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Generalized least squares fit by REML
##   Model: Daily.Mean.PM2.5.Concentration ~ Date 
##   Data: PM2.5 
##        AIC      BIC    logLik
##   1865.202 1876.698 -929.6011
## 
## Coefficients:
##                Value Std.Error   t-value p-value
## (Intercept) 98.57796  34.60285  2.848840  0.0047
## Date        -0.00513   0.00195 -2.624999  0.0091
## 
##  Correlation: 
##      (Intr)
## Date -1    
## 
## Standardized residuals:
##        Min         Q1        Med         Q3        Max 
## -2.3531000 -0.6348100 -0.1153454  0.6383004  3.4063068 
## 
## Residual standard error: 3.584321 
## Degrees of freedom: 343 total; 341 residual
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{anova}\NormalTok{(PM252018.mixed, PM252018.fixed)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                Model df      AIC      BIC    logLik   Test  L.Ratio
## PM252018.mixed     1  5 1756.622 1775.781 -873.3110                
## PM252018.fixed     2  3 1865.202 1876.698 -929.6011 1 vs 2 112.5802
##                p-value
## PM252018.mixed        
## PM252018.fixed  <.0001
\end{verbatim}

Which model is better?

\begin{quote}
ANSWER: The mixed effects model has a lower AIC value (1756.62 vs
1865.2); hence, it is a better fit than the fixed effect model.
\end{quote}

\subsection{Run a Mann-Kendall test}\label{run-a-mann-kendall-test}

Research question: Is there a trend in total N surface concentrations in
Peter and Paul lakes?

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Duplicate the Mann-Kendall test we ran for total P in class, this time
  with total N for both lakes. Make sure to run a test for changepoints
  in the datasets (and run a second one if a second change point is
  likely).
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Wrangle our dataset}
\NormalTok{PeterPaul.tN.surface <-}\StringTok{ }
\StringTok{  }\NormalTok{NTL_TER_raw_ChemistryNutr_PeterPaul }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(lakename, sampledate, depth, tn_ug) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(depth }\OperatorTok{==}\StringTok{ }\DecValTok{0}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(tn_ug))}

\KeywordTok{ggplot}\NormalTok{(PeterPaul.tN.surface, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ sampledate, }\DataTypeTok{y =}\NormalTok{ tn_ug, }\DataTypeTok{color =}\NormalTok{ lakename)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\KeywordTok{expression}\NormalTok{(}\StringTok{"Date"}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\KeywordTok{expression}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{"Total Nitrogen Concentration (\textbackslash{}U003BCg/lt)"}\NormalTok{))) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Peter Paul Lakes Total Nitrogen Concentration"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_color_manual}\NormalTok{(}\DataTypeTok{values =} \KeywordTok{c}\NormalTok{(}\StringTok{"#7fcdbb"}\NormalTok{, }\StringTok{"#253494"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{A08_TimeSeries_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Split dataset by lake}
\NormalTok{Peter.tN.surface <-}\StringTok{ }\KeywordTok{filter}\NormalTok{(PeterPaul.tN.surface, lakename }\OperatorTok{==}\StringTok{ "Peter Lake"}\NormalTok{)}

\KeywordTok{ggplot}\NormalTok{(Peter.tN.surface, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ sampledate, }\DataTypeTok{y =}\NormalTok{ tn_ug)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{color =} \KeywordTok{c}\NormalTok{(}\StringTok{"#253494"}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\KeywordTok{expression}\NormalTok{(}\StringTok{"Date"}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\KeywordTok{expression}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{"Total Nitrogen Concentration (\textbackslash{}U003BCg/lt)"}\NormalTok{))) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Peter Lake Total Nitrogen Concentration"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A08_TimeSeries_files/figure-latex/unnamed-chunk-5-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Paul.tN.surface <-}\StringTok{ }\KeywordTok{filter}\NormalTok{(PeterPaul.tN.surface, lakename }\OperatorTok{==}\StringTok{ "Paul Lake"}\NormalTok{)}

\KeywordTok{ggplot}\NormalTok{(Paul.tN.surface, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ sampledate, }\DataTypeTok{y =}\NormalTok{ tn_ug)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{color =} \KeywordTok{c}\NormalTok{(}\StringTok{"#7fcdbb"}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\KeywordTok{expression}\NormalTok{(}\StringTok{"Date"}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\KeywordTok{expression}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{"Total Nitrogen Concentration (\textbackslash{}U003BCg/lt)"}\NormalTok{))) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Paul Lake Total Nitrogen Concentration"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A08_TimeSeries_files/figure-latex/unnamed-chunk-5-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Run a Mann-Kendall test for Peter Lake}
\KeywordTok{mk.test}\NormalTok{(Peter.tN.surface}\OperatorTok{$}\NormalTok{tn_ug)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Mann-Kendall trend test
## 
## data:  Peter.tN.surface$tn_ug
## z = 7.2927, n = 98, p-value = 3.039e-13
## alternative hypothesis: true S is not equal to 0
## sample estimates:
##            S         varS          tau 
## 2.377000e+03 1.061503e+05 5.001052e-01
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# There is a significant trend in total N surface concentrations in Peter }
\CommentTok{# lake (Mann-Kendall trend test, z = 7.2927, n = 98, p-value = 3.039e-13 < 0.05).}

\CommentTok{# Run a Pettitt's Test for changepoints in the datasets. }

\KeywordTok{pettitt.test}\NormalTok{(Peter.tN.surface}\OperatorTok{$}\NormalTok{tn_ug)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pettitt's test for single change-point detection
## 
## data:  Peter.tN.surface$tn_ug
## U* = 1884, p-value = 3.744e-10
## alternative hypothesis: two.sided
## sample estimates:
## probable change point at time K 
##                              36
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# There is a significant changepoint in total N surface concentrations in Peter lake. }
\CommentTok{# Probable change point at time K 36 = 06-02-1993 }
\CommentTok{#(Pettitt's test, U* = 1884, p-value = 3.744e-10 < 0.05).}

\CommentTok{# Run separate Mann-Kendall for each changepoint segment}

\KeywordTok{mk.test}\NormalTok{(Peter.tN.surface}\OperatorTok{$}\NormalTok{tn_ug[}\DecValTok{1}\OperatorTok{:}\DecValTok{35}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Mann-Kendall trend test
## 
## data:  Peter.tN.surface$tn_ug[1:35]
## z = -0.22722, n = 35, p-value = 0.8203
## alternative hypothesis: true S is not equal to 0
## sample estimates:
##             S          varS           tau 
##  -17.00000000 4958.33333333   -0.02857143
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# There is not a significant trend in total N surface concentrations in Peter }
\CommentTok{# lake between 05-20-1991 and 05-26-1993 }
\CommentTok{# (Mann-Kendall trend test, z = -0.22722, n = 35, p-value = 0.8203 > 0.05).}

\KeywordTok{mk.test}\NormalTok{(Peter.tN.surface}\OperatorTok{$}\NormalTok{tn_ug[}\DecValTok{36}\OperatorTok{:}\DecValTok{98}\NormalTok{]) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Mann-Kendall trend test
## 
## data:  Peter.tN.surface$tn_ug[36:98]
## z = 3.1909, n = 63, p-value = 0.001418
## alternative hypothesis: true S is not equal to 0
## sample estimates:
##            S         varS          tau 
## 5.390000e+02 2.842700e+04 2.759857e-01
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# There is not a significant trend in total N surface concentrations in Peter }
\CommentTok{# lake between 06-02-1993 and 08-16-1999 }
\CommentTok{# (Mann-Kendall trend test, z = 3.1909, n = 63, p-value = 0.001418 < 0.05).}

\CommentTok{# Is there a second change point?}
\KeywordTok{pettitt.test}\NormalTok{(Peter.tN.surface}\OperatorTok{$}\NormalTok{tn_ug[}\DecValTok{1}\OperatorTok{:}\DecValTok{35}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pettitt's test for single change-point detection
## 
## data:  Peter.tN.surface$tn_ug[1:35]
## U* = 72, p-value = 0.9879
## alternative hypothesis: two.sided
## sample estimates:
## probable change point at time K 
##                              30
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# There is not a significant changepoint in total N surface concentrations in Peter lake }
\CommentTok{# between 05-20-1991 and 05-26-1993. (Pettitt's test, U* = 72, p-value = 0.9879).}

\KeywordTok{pettitt.test}\NormalTok{(Peter.tN.surface}\OperatorTok{$}\NormalTok{tn_ug[}\DecValTok{36}\OperatorTok{:}\DecValTok{98}\NormalTok{]) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pettitt's test for single change-point detection
## 
## data:  Peter.tN.surface$tn_ug[36:98]
## U* = 560, p-value = 0.001213
## alternative hypothesis: two.sided
## sample estimates:
## probable change point at time K 
##                              21
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# There is a significant changepoint in total N surface concentrations in Peter }
\CommentTok{# lake between 06-02-1993 and 08-16-1999. Probable change point at time }
\CommentTok{# K 21 = 06-22-1994 (Pettitt's test, U* = 560, p-value = 0.001213 < 0.05).}

\CommentTok{# Run another Mann-Kendall for the second change point}
\KeywordTok{mk.test}\NormalTok{(Peter.tN.surface}\OperatorTok{$}\NormalTok{tn_ug[}\DecValTok{36}\OperatorTok{:}\DecValTok{55}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Mann-Kendall trend test
## 
## data:  Peter.tN.surface$tn_ug[36:55]
## z = -1.2004, n = 20, p-value = 0.23
## alternative hypothesis: true S is not equal to 0
## sample estimates:
##     S  varS   tau 
## -38.0 950.0  -0.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# There is not a significant trend in total N surface concentrations in Peter }
\CommentTok{# lake between 06-02-1993 and 06-15-1994 }
\CommentTok{# (Mann-Kendall trend test, z = -1.2004, n = 20, p-value = 0.23 > 0.05).}

\KeywordTok{mk.test}\NormalTok{(Peter.tN.surface}\OperatorTok{$}\NormalTok{tn_ug[}\DecValTok{56}\OperatorTok{:}\DecValTok{98}\NormalTok{]) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Mann-Kendall trend test
## 
## data:  Peter.tN.surface$tn_ug[56:98]
## z = 0.48141, n = 43, p-value = 0.6302
## alternative hypothesis: true S is not equal to 0
## sample estimates:
##            S         varS          tau 
## 4.700000e+01 9.130333e+03 5.204873e-02
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# There is not a significant trend in total N surface concentrations in Peter }
\CommentTok{# lake between 06-22-1994 and 08-16-1999 }
\CommentTok{# (Mann-Kendall trend test, z = 0.48141, n = 43, p-value = 0.6302 > 0.05).}


\CommentTok{# Is there a third change point?}
\KeywordTok{pettitt.test}\NormalTok{(Peter.tN.surface}\OperatorTok{$}\NormalTok{tn_ug[}\DecValTok{36}\OperatorTok{:}\DecValTok{55}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pettitt's test for single change-point detection
## 
## data:  Peter.tN.surface$tn_ug[36:55]
## U* = 42, p-value = 0.5673
## alternative hypothesis: two.sided
## sample estimates:
## probable change point at time K 
##                              12
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# There is not a significant changepoint in total N surface concentrations in Peter lake }
\CommentTok{# between 06-02-1993 and 06-15-1994. (Pettitt's test, U* = 42, p-value = 0.5673).}

\KeywordTok{pettitt.test}\NormalTok{(Peter.tN.surface}\OperatorTok{$}\NormalTok{tn_ug[}\DecValTok{56}\OperatorTok{:}\DecValTok{98}\NormalTok{]) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pettitt's test for single change-point detection
## 
## data:  Peter.tN.surface$tn_ug[56:98]
## U* = 128, p-value = 0.5974
## alternative hypothesis: two.sided
## sample estimates:
## probable change point at time K 
##                              21
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# There is not a significant changepoint in total N surface concentrations in Peter lake }
\CommentTok{# between 06-22-1994 and 08-16-1999. (Pettitt's test, U* = 42, p-value = 0.5673).}

\CommentTok{# In Peter lake data visually it can be seen a decreasing trend after point 84 (1996-06-25), }
\CommentTok{# so we check for that.}

\KeywordTok{mk.test}\NormalTok{(Peter.tN.surface}\OperatorTok{$}\NormalTok{tn_ug[}\DecValTok{56}\OperatorTok{:}\DecValTok{84}\NormalTok{]) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Mann-Kendall trend test
## 
## data:  Peter.tN.surface$tn_ug[56:84]
## z = 0.69405, n = 29, p-value = 0.4877
## alternative hypothesis: true S is not equal to 0
## sample estimates:
##            S         varS          tau 
## 3.800000e+01 2.842000e+03 9.359606e-02
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# There is not a significant trend in total N surface concentrations in Peter lake between 06-22-1994 }
\CommentTok{# and 06-25-1996 (Mann-Kendall trend test, z = 0.69405, n = 29, p-value = 0.4877 > 0.05).}

\KeywordTok{mk.test}\NormalTok{(Peter.tN.surface}\OperatorTok{$}\NormalTok{tn_ug[}\DecValTok{84}\OperatorTok{:}\DecValTok{98}\NormalTok{]) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Mann-Kendall trend test
## 
## data:  Peter.tN.surface$tn_ug[84:98]
## z = -2.2764, n = 15, p-value = 0.02282
## alternative hypothesis: true S is not equal to 0
## sample estimates:
##          S       varS        tau 
## -47.000000 408.333333  -0.447619
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# There is a significant trend in total N surface concentrations in Peter lake between }
\CommentTok{# 06-25-1996 and 08-16-1999 (Mann-Kendall trend test, z = -2.2764, n = 15, p-value = 0.02282 < 0.05).}

\CommentTok{# Run a Mann-Kendall test for Paul Lake}

\KeywordTok{mk.test}\NormalTok{(Paul.tN.surface}\OperatorTok{$}\NormalTok{tn_ug)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Mann-Kendall trend test
## 
## data:  Paul.tN.surface$tn_ug
## z = -0.1572, n = 99, p-value = 0.8751
## alternative hypothesis: true S is not equal to 0
## sample estimates:
##             S          varS           tau 
## -5.300000e+01  1.094170e+05 -1.092558e-02
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# There is not a significant trend in total N surface concentrations in Paul }
\CommentTok{# lake (Mann-Kendall trend test, z = -0.1572, n = 99, p-value = 0.8751 > 0.05).}

\CommentTok{# Run a Pettitt's Test for changepoints in the datasets. }

\KeywordTok{pettitt.test}\NormalTok{(Paul.tN.surface}\OperatorTok{$}\NormalTok{tn_ug)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pettitt's test for single change-point detection
## 
## data:  Paul.tN.surface$tn_ug
## U* = 704, p-value = 0.09624
## alternative hypothesis: two.sided
## sample estimates:
## probable change point at time K 
##                              16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# There is not a significant changepoint in total N surface concentrations in Paul lake. }
\CommentTok{# (Pettitt's test, U* = 704, p-value = 0.09624 > 0.05).}
\end{Highlighting}
\end{Shaded}

What are the results of this test?

\begin{quote}
ANSWER: In Peter Lake, there is a significant increasing trend in total
N surface concentrations between 05-20-1991 and 08-16-1999 (Mann-Kendall
trend test, z = 7.2927, n = 98, p-value = 3.039e-13 \textless{} 0.05).
There is also a significant changepoint in total N surface
concentrations in Peter lake at time K 36 = 06-02-1993 (Pettitt's test,
U = 1884, p-value = 3.744e-10 \textless{} 0.05), and a second one at
time K 21 = 06-22-1994 (Pettitt's test, U = 560, p-value = 0.001213
\textless{} 0.05).
\end{quote}

\begin{quote}
There is also a significant decreasing trend in total N surface
concentrations between 06-25-1996 and 08-16-1999 (Mann-Kendall trend
test, z = -2.2764, n = 15, p-value = 0.02282 \textless{} 0.05), which
was identified visually.
\end{quote}

\begin{quote}
In Paul Lake, there is not a significant trend in total N surface
concentrations (Mann-Kendall trend test, z = -0.1572, n = 99, p-value =
0.8751 \textgreater{} 0.05).
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Generate a graph that illustrates the TN concentrations over time,
  coloring by lake and adding vertical line(s) representing
  changepoint(s).
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(PeterPaul.tN.surface, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ sampledate, }\DataTypeTok{y =}\NormalTok{ tn_ug, }\DataTypeTok{color =}\NormalTok{ lakename)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\KeywordTok{expression}\NormalTok{(}\StringTok{"Date"}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\KeywordTok{expression}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{"Total Nitrogen Concentration (\textbackslash{}U003BCg/lt)"}\NormalTok{))) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Peter Paul Lakes Total Nitrogen Concentration"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_color_manual}\NormalTok{(}\DataTypeTok{values =} \KeywordTok{c}\NormalTok{(}\StringTok{"#7fcdbb"}\NormalTok{, }\StringTok{"#253494"}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_vline}\NormalTok{(}\DataTypeTok{xintercept=}\KeywordTok{as.Date}\NormalTok{(}\StringTok{"1993/06/02"}\NormalTok{), }\DataTypeTok{color=} \StringTok{"#253494"}\NormalTok{, }\DataTypeTok{lty=}\DecValTok{2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_vline}\NormalTok{(}\DataTypeTok{xintercept=}\KeywordTok{as.Date}\NormalTok{(}\StringTok{"1994/06/22"}\NormalTok{), }\DataTypeTok{color=} \StringTok{"#253494"}\NormalTok{, }\DataTypeTok{lty=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A08_TimeSeries_files/figure-latex/unnamed-chunk-6-1.pdf}


\end{document}
